name: Generate Readme

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/readme.yml"
      - "doc/templates/readme/*"
      - "doc/resources/*"
      - "fmt/**/*.nu"

defaults:
  run:
    shell: nu {0}

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Nushell
        uses: hustcer/setup-nu@v3

      - name: Generate Readme
        run: |
          nu .github/scripts/generate-readme.nu

      - name: Commit & push changes
        run: |
          git config --global user.name "nucleus"
          git config --global user.email "nucleus@users.noreply.github.com"
          git add README.md
          try {git commit -m "Update README"}
          git push
